// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-sz0DNOb-wmfjAn5xV2mN2W9o-gNYZEA',
    appId: '1:340707129697:web:cdfb9d4f0853eeaf11ad20',
    messagingSenderId: '340707129697',
    projectId: 'hitup-fc62d',
    authDomain: 'hitup-fc62d.firebaseapp.com',
    databaseURL: 'https://hitup-fc62d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hitup-fc62d.firebasestorage.app',
    measurementId: 'G-HC852NQDEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRgd6wzdXKwflB8LVygD8A7fuJkokYwfg',
    appId: '1:340707129697:android:93a200d5ba2ee8d511ad20',
    messagingSenderId: '340707129697',
    projectId: 'hitup-fc62d',
    databaseURL: 'https://hitup-fc62d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hitup-fc62d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaHTx7Pbz40_pt5jxniFuChmOv6vrt_kw',
    appId: '1:340707129697:ios:f6869d9ea9f5985711ad20',
    messagingSenderId: '340707129697',
    projectId: 'hitup-fc62d',
    databaseURL: 'https://hitup-fc62d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hitup-fc62d.firebasestorage.app',
    iosClientId: '340707129697-iic825blcq33dt6se3fhsld3hr9lk5gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.hitupChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaHTx7Pbz40_pt5jxniFuChmOv6vrt_kw',
    appId: '1:340707129697:ios:f6869d9ea9f5985711ad20',
    messagingSenderId: '340707129697',
    projectId: 'hitup-fc62d',
    databaseURL: 'https://hitup-fc62d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hitup-fc62d.firebasestorage.app',
    iosClientId: '340707129697-iic825blcq33dt6se3fhsld3hr9lk5gb.apps.googleusercontent.com',
    iosBundleId: 'com.example.hitupChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-sz0DNOb-wmfjAn5xV2mN2W9o-gNYZEA',
    appId: '1:340707129697:web:d10d63708a7b15fb11ad20',
    messagingSenderId: '340707129697',
    projectId: 'hitup-fc62d',
    authDomain: 'hitup-fc62d.firebaseapp.com',
    databaseURL: 'https://hitup-fc62d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hitup-fc62d.firebasestorage.app',
    measurementId: 'G-FPXD2QC5P0',
  );

}